export default [ 
  [ 
     -1001364392463,
     { 
        "@type":"chat",
        "id":-1001364392463,
        "type":{ 
           "@type":"chatTypeSupergroup",
           "supergroup_id":1364392463,
           "is_channel":true
        },
        "title":"NBA. Новости",
        "photo":{ 
           "@type":"chatPhoto",
           "small":{ 
              "@type":"file",
              "id":101,
              "size":0,
              "expected_size":0,
              "local":{ 
                 "@type":"localFile",
                 "path":"",
                 "can_be_downloaded":true,
                 "can_be_deleted":false,
                 "is_downloading_active":false,
                 "is_downloading_completed":false,
                 "download_offset":0,
                 "downloaded_prefix_size":0,
                 "downloaded_size":0
              },
              "remote":{ 
                 "@type":"remoteFile",
                 "id":"AQADAgATNwgzDgAEAgAD8fUH2hb___8DrAxhLic0MaycAAIWBA",
                 "is_uploading_active":false,
                 "is_uploading_completed":true,
                 "uploaded_size":0
              }
           },
           "big":{ 
              "@type":"file",
              "id":102,
              "size":0,
              "expected_size":0,
              "local":{ 
                 "@type":"localFile",
                 "path":"",
                 "can_be_downloaded":true,
                 "can_be_deleted":false,
                 "is_downloading_active":false,
                 "is_downloading_completed":false,
                 "download_offset":0,
                 "downloaded_prefix_size":0,
                 "downloaded_size":0
              },
              "remote":{ 
                 "@type":"remoteFile",
                 "id":"AQADAgATNwgzDgAEAwAD8fUH2hb___8DrAxhLic0Ma6cAAIWBA",
                 "is_uploading_active":false,
                 "is_uploading_completed":true,
                 "uploaded_size":0
              }
           }
        },
        "permissions":{ 
           "@type":"chatPermissions",
           "can_send_messages":false,
           "can_send_media_messages":false,
           "can_send_polls":false,
           "can_send_other_messages":false,
           "can_add_web_page_previews":false,
           "can_change_info":false,
           "can_invite_users":false,
           "can_pin_messages":false
        },
        "last_message":{ 
           "@type":"message",
           "id":38959841280,
           "sender_user_id":0,
           "chat_id":-1001364392463,
           "is_outgoing":false,
           "can_be_edited":false,
           "can_be_forwarded":true,
           "can_be_deleted_only_for_self":false,
           "can_be_deleted_for_all_users":false,
           "is_channel_post":true,
           "contains_unread_mention":false,
           "date":1573326800,
           "edit_date":0,
           "reply_to_message_id":0,
           "ttl":0,
           "ttl_expires_in":0,
           "via_bot_user_id":0,
           "author_signature":"",
           "views":254,
           "media_album_id":"0",
           "content":{ 
              "@type":"messagePhoto",
              "photo":{ 
                 "@type":"photo",
                 "has_stickers":false,
                 "minithumbnail":{ 
                    "@type":"minithumbnail",
                    "width":23,
                    "height":40,
                    "data":"/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAXACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCt9jVrdJFyN3Q9c+3aoWtyp2nIPuDWjaRo9iI2Y4JIO3tnoar5yoSfD44BHUfjSGVhBhMluO5A/wAaUImMDk+pP9BV/wCy7IjGh+VvmOeoFQgeTxApBPVz1oAhx5S84Df3cc/rRT48LKWLfMvqMmik7FJXNGBTDFlSNpHCgdyf/r0kUEbyTbo1IDd/pRRTJJTF+83buDxjHtUUlhAiGQAgqM9aKKAIrVVnuCQBggckdaKKKhJDbP/Z"
                 },
                 "sizes":[ 
                    { 
                       "@type":"photoSize",
                       "type":"m",
                       "photo":{ 
                          "@type":"file",
                          "id":211,
                          "size":23965,
                          "expected_size":23965,
                          "local":{ 
                             "@type":"localFile",
                             "path":"",
                             "can_be_downloaded":true,
                             "can_be_deleted":false,
                             "is_downloading_active":false,
                             "is_downloading_completed":false,
                             "download_offset":0,
                             "downloaded_prefix_size":0,
                             "downloaded_size":0
                          },
                          "remote":{ 
                             "@type":"remoteFile",
                             "id":"AgADAgADUK0xG9QIOEpiYKF5jF9qJrPNtw8ABAEAAwIAA20AA16PBgABFgQ",
                             "is_uploading_active":false,
                             "is_uploading_completed":true,
                             "uploaded_size":23965
                          }
                       },
                       "width":320,
                       "height":180
                    },
                    { 
                       "@type":"photoSize",
                       "type":"x",
                       "photo":{ 
                          "@type":"file",
                          "id":212,
                          "size":91441,
                          "expected_size":91441,
                          "local":{ 
                             "@type":"localFile",
                             "path":"",
                             "can_be_downloaded":true,
                             "can_be_deleted":false,
                             "is_downloading_active":false,
                             "is_downloading_completed":false,
                             "download_offset":0,
                             "downloaded_prefix_size":0,
                             "downloaded_size":0
                          },
                          "remote":{ 
                             "@type":"remoteFile",
                             "id":"AgADAgADUK0xG9QIOEpiYKF5jF9qJrPNtw8ABAEAAwIAA3gAA2CPBgABFgQ",
                             "is_uploading_active":false,
                             "is_uploading_completed":true,
                             "uploaded_size":91441
                          }
                       },
                       "width":800,
                       "height":450
                    },
                    { 
                       "@type":"photoSize",
                       "type":"y",
                       "photo":{ 
                          "@type":"file",
                          "id":213,
                          "size":168496,
                          "expected_size":168496,
                          "local":{ 
                             "@type":"localFile",
                             "path":"",
                             "can_be_downloaded":true,
                             "can_be_deleted":false,
                             "is_downloading_active":false,
                             "is_downloading_completed":false,
                             "download_offset":0,
                             "downloaded_prefix_size":0,
                             "downloaded_size":0
                          },
                          "remote":{ 
                             "@type":"remoteFile",
                             "id":"AgADAgADUK0xG9QIOEpiYKF5jF9qJrPNtw8ABAEAAwIAA3kAA1-PBgABFgQ",
                             "is_uploading_active":false,
                             "is_uploading_completed":true,
                             "uploaded_size":168496
                          }
                       },
                       "width":1280,
                       "height":720
                    }
                 ]
              },
              "caption":{ 
                 "@type":"formattedText",
                 "text":"Богданович: Мне говорили о шумной толпе \'Юты\', но я не представлял, что будет так громко на каждом матче\n#NBANews #NBA #Jazz\n\nФорварду \'Юты\' Бояну Богдановичу после победного баззера против Милуоки (103:100) было трудно дать интервью из-за шума болельщиков на арене. \n \nОни говорили об этой толпе, когда я подписал контракт с Джаз, но я мог подумать, что будет так громко на каждой игре, - сказал Богданович после матча.\n\nvk.com",
                 "entities":[ 
                    { 
                       "@type":"textEntity",
                       "offset":105,
                       "length":8,
                       "type":{ 
                          "@type":"textEntityTypeHashtag"
                       }
                    },
                    { 
                       "@type":"textEntity",
                       "offset":114,
                       "length":4,
                       "type":{ 
                          "@type":"textEntityTypeHashtag"
                       }
                    },
                    { 
                       "@type":"textEntity",
                       "offset":119,
                       "length":5,
                       "type":{ 
                          "@type":"textEntityTypeHashtag"
                       }
                    },
                    { 
                       "@type":"textEntity",
                       "offset":428,
                       "length":6,
                       "type":{ 
                          "@type":"textEntityTypeTextUrl",
                          "url":"https://vk.com/wall-28402905_2543376"
                       }
                    }
                 ]
              },
              "is_secret":false
           }
        },
        "order":"6757387151920369955",
        "is_pinned":false,
        "is_marked_as_unread":false,
        "is_sponsored":false,
        "can_be_deleted_only_for_self":false,
        "can_be_deleted_for_all_users":false,
        "can_be_reported":true,
        "default_disable_notification":false,
        "unread_count":27,
        "last_read_inbox_message_id":38931529728,
        "last_read_outbox_message_id":2251799812636672,
        "unread_mention_count":0,
        "notification_settings":{ 
           "@type":"chatNotificationSettings",
           "use_default_mute_for":false,
           "mute_for":574155795,
           "use_default_sound":true,
           "sound":"default",
           "use_default_show_preview":true,
           "show_preview":false,
           "use_default_disable_pinned_message_notifications":true,
           "disable_pinned_message_notifications":false,
           "use_default_disable_mention_notifications":true,
           "disable_mention_notifications":false
        },
        "pinned_message_id":0,
        "reply_markup_message_id":0,
        "client_data":"",
        "@extra":{ 
           "query_id":7
        }
     }
  ],
  [ 
     545449089,
     { 
        "@type":"chat",
        "id":545449089,
        "type":{ 
           "@type":"chatTypePrivate",
           "user_id":545449089
        },
        "title":"Наташа",
        "photo":{ 
           "@type":"chatPhoto",
           "small":{ 
              "@type":"file",
              "id":3,
              "size":0,
              "expected_size":0,
              "local":{ 
                 "@type":"localFile",
                 "path":"",
                 "can_be_downloaded":true,
                 "can_be_deleted":false,
                 "is_downloading_active":false,
                 "is_downloading_completed":false,
                 "download_offset":0,
                 "downloaded_prefix_size":0,
                 "downloaded_size":0
              },
              "remote":{ 
                 "@type":"remoteFile",
                 "id":"AQADAgADtKcxG4HkgiAACMh9XA8ABAIAA4HkgiAABLfK_y6sBdF0m8QAAhYE",
                 "is_uploading_active":false,
                 "is_uploading_completed":true,
                 "uploaded_size":0
              }
           },
           "big":{ 
              "@type":"file",
              "id":4,
              "size":0,
              "expected_size":0,
              "local":{ 
                 "@type":"localFile",
                 "path":"",
                 "can_be_downloaded":true,
                 "can_be_deleted":false,
                 "is_downloading_active":false,
                 "is_downloading_completed":false,
                 "download_offset":0,
                 "downloaded_prefix_size":0,
                 "downloaded_size":0
              },
              "remote":{ 
                 "@type":"remoteFile",
                 "id":"AQADAgADtKcxG4HkgiAACMh9XA8ABAMAA4HkgiAABLfK_y6sBdF0ncQAAhYE",
                 "is_uploading_active":false,
                 "is_uploading_completed":true,
                 "uploaded_size":0
              }
           }
        },
        "permissions":{ 
           "@type":"chatPermissions",
           "can_send_messages":true,
           "can_send_media_messages":true,
           "can_send_polls":true,
           "can_send_other_messages":true,
           "can_add_web_page_previews":true,
           "can_change_info":false,
           "can_invite_users":false,
           "can_pin_messages":false
        },
        "last_message":{ 
           "@type":"message",
           "id":113566023680,
           "sender_user_id":545449089,
           "chat_id":545449089,
           "is_outgoing":false,
           "can_be_edited":false,
           "can_be_forwarded":true,
           "can_be_deleted_only_for_self":true,
           "can_be_deleted_for_all_users":true,
           "is_channel_post":false,
           "contains_unread_mention":false,
           "date":1573323150,
           "edit_date":0,
           "reply_to_message_id":0,
           "ttl":0,
           "ttl_expires_in":0,
           "via_bot_user_id":0,
           "author_signature":"",
           "views":0,
           "media_album_id":"0",
           "content":{ 
              "@type":"messageText",
              "text":{ 
                 "@type":"formattedText",
                 "text":"Слово",
                 "entities":[ 

                 ]
              }
           }
        },
        "order":"6757371475289810705",
        "is_pinned":false,
        "is_marked_as_unread":false,
        "is_sponsored":false,
        "can_be_deleted_only_for_self":true,
        "can_be_deleted_for_all_users":true,
        "can_be_reported":false,
        "default_disable_notification":false,
        "unread_count":2,
        "last_read_inbox_message_id":113465360384,
        "last_read_outbox_message_id":113539809280,
        "unread_mention_count":0,
        "notification_settings":{ 
           "@type":"chatNotificationSettings",
           "use_default_mute_for":true,
           "mute_for":0,
           "use_default_sound":true,
           "sound":"default",
           "use_default_show_preview":true,
           "show_preview":false,
           "use_default_disable_pinned_message_notifications":true,
           "disable_pinned_message_notifications":false,
           "use_default_disable_mention_notifications":true,
           "disable_mention_notifications":false
        },
        "pinned_message_id":0,
        "reply_markup_message_id":0,
        "client_data":"",
        "@extra":{ 
           "query_id":8
        }
     }
  ]
]